# Generated by Django 3.2.7 on 2021-12-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20211130_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='allow_pets',
        ),
    ]
