# Generated by Django 3.2.7 on 2021-12-03 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_remove_listing_allow_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
